### ISSUE TITLE
新建议

### ISSUE THREAD

**Issue by tinyvan** [Dennishaha/JZip#10]
拖选若干文件后,选择添加到文件夹,可否添加一个功能查看已选文件?

**Comment by tinyvan** [comment]
另外......希望有反选功能...

**Comment by Dennishaha** [comment]
说说具体流程

**Comment by tinyvan** [comment]
只略懂c#,bat的语法太乱,我不太懂...
不如找找gtr-0000老兄?
@gtr-0000

**Comment by Dennishaha** [comment]
c#大佬

**Comment by 9-2-1** [comment]
> 流程流程,我是c#程序员,bat的语法太乱,我不太懂...
> 不如找找gtr-0000老兄?
> @gtr-0000

# ?
