### ISSUE TITLE
设置为英文后jzip不能用

### ISSUE THREAD

**Issue by 9-2-1** [Dennishaha/JZip#13]
如题，语言设定改为英文后无法`新建压缩文件`和`打开压缩文件`(就是两个按钮失效)
目前不知道是什么导致的bug

**Comment by Dennishaha** [comment]
在英文模式下，选择的文件只能带英文字符。
目前没想到好方法去支持非英文字符。

**Comment by 9-2-1** [comment]
然而在我这边就算是选择`jzip.cmd`本身都无法新建压缩文件

**Comment by Dennishaha** [comment]
可以提供下错误输出吗 和环境

**Comment by 9-2-1** [comment]
`Microsoft Windows [版本 10.0.17134.590]` `x64`
![image](https://user-images.githubusercontent.com/33796749/53283700-21dfbd80-3785-11e9-8ef8-178139b846f6.png)
![image](https://user-images.githubusercontent.com/33796749/53283705-2c9a5280-3785-11e9-9a43-f3beae29517a.png)
操作后，只有窗口底部会有一条看不清的错误消息闪过
试着pause了一下
``` diff
@@ -177,6 +177,7 @@
if "%key%"== "1" ( call :SetPath list
 ) else if "%key%"== "4" ( call "%dir.jzip%\Parts\Set.cmd"
 )

+pause
 ::Çå³ýÒÑÓбäÁ¿²¢ÖØÆô
 ::start "" /b /i cmd /c "%path.jzip.launcher%" & cls & exit /b
 goto :BASIC
```
![image](https://user-images.githubusercontent.com/33796749/53283725-7daa4680-3785-11e9-9f7f-a4872d4e9c00.png)

**Comment by Dennishaha** [comment]
Jzip.cmd L186 加一行 set key=

:SetPath
set key=                %=添加在这里=%
call "%dir.jzip%\Function\Select_File.cmd" key
if defined key call :Set_Info %~1 "!key!"
goto :EOF

试下有没有效果

**Comment by 9-2-1** [comment]
没有，还是一样
