### ISSUE TITLE
可以在安装的时候向注册表添加

### ISSUE THREAD

**Issue by ghost** [Dennishaha/JZip#2]

**Comment by Dennishaha** [comment]
目前写入注册表的方式是启动时读取已有注册表（若有）然后刷新一遍，这样可能不是最好的方案，
也可能会影响效率，但可以保证每次运行的时候不出错误。

若您有具体的实现流程，可以在 issues 中提出。
在新的方案确定下来之前，应该会保持原有的方案。
感谢您的反馈，Dennishaha。
