### ISSUE TITLE
压缩文件查看的排版有问题

### ISSUE THREAD

**Issue by tinyvan** [Dennishaha/JZip#3]
我认为,文件名应在前,其他信息应在后,最好能够自定义
只是个人看法,如果技术上难以达到的话可以忽略

**Comment by Dennishaha** [comment]
目前的排版是根据 7z rar 命令行 生成的输出进行排版的。期间也考虑做过更好的排版 比如说 文件名在第一位 然后是类型和日期大小 这样合乎 Windows 资源管理器的默认排布 也可以做个切换标签。

但是目前没有找到很好的实现方式，比如说补齐空格排版那些，在不调用第三方情况下实现可能会有效率问题。之前做过个限制单行输出长度的 （中文和英文长度不一样，字符串不好按字节数切割）。

我们会寻求改进的最好的实现方式。
Dennis 祝您新年快乐，感谢您的反馈使这个项目变得更好。
