### ISSUE TITLE
可否详细更新内容?

### ISSUE THREAD

**Issue by tinyvan** [Dennishaha/JZip#4]
每次更新都是那几句话,到底更新了啥我也不清楚,不能详细些么?
毕竟可提升空间很大,我一直都很期待的

**Comment by Dennishaha** [comment]
我目前更新日志是写在 commits 里边的可能比较难让人注意到，嗯，要改正。
不过有时我写着写着我就忘记了之前动过什么地方... 一些无关紧要的代码我就没有提及了，还有代码细节。更新描述只写出了大概的用户方面的体验的改变。

以后我会在 JZip 更新器里边详细列出更新日志的。
感谢您对 JZip 项目的支持和给予了浓厚的期望，有了您的支持，我们会做的更好的！
Dennishaha.
