### ISSUE TITLE
不能打开压缩包的子卷

### ISSUE THREAD

**Issue by tinyvan** [Dennishaha/JZip#5]
RT,比如****.r00,打开主卷一样可以,但如果能直接打开子卷就更好了

**Comment by Dennishaha** [comment]
这个问题我测试下，嗯，很有价值

**Comment by 9-2-1** [comment]
从子卷文件名去推测主卷文件名
类似于
``` batchfile
for /l %%f in (%filename%) do (
    for /l %%a in (101,1,199) do (
        set a=%%a
        if "%%~xf"==".r!a:~1!" set filename=%%~dpnf.r00
    )
)
```

**Comment by tinyvan** [comment]
> 子从卷文件名去同性质的主卷文件名
> 类似于
> 
> ```batchfile
> for / l %% f in（％filename％）do（
>      for / l %% a in in（101,1,199）do（
>          set  a = %% a
>          if if  “ %% ~xf ” == “。r ！a：〜1！“  set  filename = %% ~dpnf.r00
>     ）
> ）
> ```

此问题作者已经解决了,你来晚了
