### ISSUE TITLE
关于新UI问题

### ISSUE THREAD

**Issue by tinyvan** [Dennishaha/JZip#6]
由于我对Jzip未来的憧憬,我希望可以为Jzip贡献一份力量.
/
/
/
/
But.....
/
作者你可真是用心做程序,用脚做UI啊,这几个图标也太随手了
此为我用两只脚做的UI,拿去看看吧,望采纳

[Components.zip](https://github.com/Dennishaha/JZip/files/2848468/Components.zip)

**Comment by Dennishaha** [comment]
感谢您花了很多心思绘制 jzip 图标，设计还不错。
emm, 但合并主分支我持保留意见，我可能希望是更圆润点的【手动滑稽】....
目前来说，缺少各文件类型关联的图标，这个是需求更大的，，，
我是不会告诉你JZ两个字真的用手画的，哼~~~
今天不是Dennishaha，是坐与放寬【手动阴险】

**Comment by tinyvan** [comment]
我一直以为Dennishaha就是贴吧那个坐与放宽......额........
然而请你认清一个事实
一个16x16的图标连曲线都画不出来好戈?
硬硬的更简约,有质感
如果圆润的话.........
/
/
/
看来你是弯的

**Comment by Dennishaha** [comment]
不。。。
是一个人，换种叫法。。
64x64也行
128x128更好 【手动滑稽】
高分屏幕友好
啦啦啦

**Comment by tinyvan** [comment]
128的想法不太实际,因为贴图占用几乎比程序高数倍,你这在线更新的速度堪忧

**Comment by Dennishaha** [comment]
我想到解决方案了，将在未来版本考虑引入图标切换，可选择多套图标。

**Comment by tinyvan** [comment]
那么,你会把我的填进去么?

**Comment by tinyvan** [comment]
你这个圆润化....我还是用自己做的吧

**Comment by Dennishaha** [comment]
对 可以选择切换

**Comment by tinyvan** [comment]
[add.zip](https://github.com/Dennishaha/JZip/files/2849977/add.zip)
新圆滑UI,由原来16x16改为了128x128,样式更形象化,色调区分,
下一步可能考虑渐变色,不同压缩文件不同色,主要从用途及压缩效果选色
