### ISSUE TITLE
新Bug反馈

### ISSUE THREAD

**Issue by tinyvan** [Dennishaha/JZip#8]
![image](https://user-images.githubusercontent.com/27542299/52908801-edb55a00-32b7-11e9-8977-d5f081077548.png)
如图,我选择了桌面文件夹
![image](https://user-images.githubusercontent.com/27542299/52908808-045bb100-32b8-11e9-859a-f24d7fcddf5d.png)
但是出现了错误
桌面实际指向%userprofile%\desktop文件夹
在其他软件中没有类似问题
另外,建议添加全选.反选功能
希望未来能够拖放,但bat限制,不知会不会有那一天

**Comment by 9-2-1** [comment]
手动修改`Function\Select_Folder.cmd`试试
``` BatchFile
<!-- :
@if "%~1"=="" echo,缺少参数%%1。& pause & goto :EOF
set "%~1="
for /f "delims=" %%a in ('mshta "%~f0"') do set "%~1=%%~a"
goto :EOF
-->
```
``` HTML
<script>
var Shell = new ActiveXObject("Shell.Application");
var Folder = Shell.BrowseForFolder(0, "请选择文件夹", 0); //起始目录为：桌面
new ActiveXObject('Scripting.FileSystemObject').GetStandardStream(1).Write(Folder ? Folder.Self.Path : "");
window.close();
</script>
```

**Comment by tinyvan** [comment]
> 修改手动`Function\Select_Folder.cmd`试试
> 
> ```batchfile
> <！ - ：
>  @ if “％~1 ” == “ ” echo，缺少参数%% 1. ＆ pause  ＆ goto：EOF 
> set  “ ％~1 = ”
>  for / f “ delims = ”  %% a in（' mshta “％~f0 ” '）设置 “ ％~1 = %% ~a ”
> 转到：EOF 
> - >
> ```
> 
> ```
> < script >
> var Shell =  new  ActiveXObject（“ Shell.Application ”）; 
> var Folder =  Shell。BrowseForFolder（0，“请选择文件夹”，0）; //起始目录为：桌面
> new  ActiveXObject（' Scripting.FileSystemObject '）。GetStandardStream（1）。写（文件夹？ 文件夹。自我。路径 ： “ ”）; 
> 窗口。close（）;
> </ script >
> ```

你好积极啊,哪都有你haha

**Comment by Dennishaha** [comment]
``

`<script>
var Shell = new ActiveXObject("Shell.Application");
var Folder = Shell.BrowseForFolder(0, "请选择文件夹", 0); //起始目录为：桌面
new ActiveXObject('Scripting.FileSystemObject').GetStandardStream(1).Write(Folder ? Folder.Self.Path : "")[window.close()];
</script>`

感谢 @gtr-0000 @2746975606 的反馈。
以上代码 不会弹出 Mshta 框。

**Comment by tinyvan** [comment]
一天后你终于回复了,感谢解决
